SA_ASP.NET_MVC_Practice/Models/Log.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations.Schema;

namespace SA_ASP.NET_MVC_Practice.Models
{
    public class Log
    {
        public int Id { get; set; }

        public DateTime StartTime { get; set; }

        public DateTime EndTime { get; set; }

        public int Milliseconds { get; set; }

        public string NameActionMethod { get; set; }
    }
}

SA_ASP.NET_MVC_Practice/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations.Schema;

namespace SA_ASP.NET_MVC_Practice.Models
{
    public enum Type
    {
        Big,
        Medium,
        Small
    }

    public class Product
    {
        [Required]
        [Display(Name = "Product id")]
        public int ProductId { get; set; }

        [Required]
        [Remote("Check", "Product", ErrorMessage = "Name is not correct")]
        public string Name { get; set; }

        [Required]
        [Range(0, 100000)]
        public decimal Price { get; set; }

        public string Description { get; set; }

        [Required]
        [Display(Name = "Type of product")]
        public Type ProductType { get; set; }

        public Detail ProductDetails { get; set; }
    }

    [ComplexType]
    public class Detail
    {
        public int DetailId { get; set; }

        public int Lenth { get; set; }

        public int Width { get; set; }

        public int Heigth { get; set; }
    }
}

SA_ASP.NET_MVC_Practice/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SA_ASP.NET_MVC_Practice;
using SA_ASP.NET_MVC_Practice.Models;

namespace SA_ASP.NET_MVC_Practice.Controllers
{
    public class LogController : Controller
    {
        private Context db = new Context();

        // GET: Log
        public ActionResult Index()
        {
            return View(db.Logs.ToList());
        }

        // GET: Log/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Log log = db.Logs.Find(id);
            if (log == null)
            {
                return HttpNotFound();
            }
            return View(log);
        }

        // GET: Log/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Log log = db.Logs.Find(id);
            if (log == null)
            {
                return HttpNotFound();
            }
            return View(log);
        }

        // POST: Log/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Log log = db.Logs.Find(id);
            db.Logs.Remove(log);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SA_ASP.NET_MVC_Practice/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SA_ASP.NET_MVC_Practice.Models;
using System.Text.RegularExpressions;
using SA_ASP.NET_MVC_Practice.Filters;

namespace SA_ASP.NET_MVC_Practice.Controllers
{
    public class ProductController : Controller
    {
        Context context = new Context();

        public ActionResult Index()
        {
            return View();
        }

        [MyActionFilter]
        public ActionResult Add(Product product)
        {
            if (product.ProductId > default(int) && !string.IsNullOrEmpty(product.Name) && product.Price > default(decimal))
            {

                context.Products.Add(new Product
                {
                    ProductId = product.ProductId,
                    Description = product.Description,
                    Name = product.Name,
                    Price = product.Price,
                    ProductType = product.ProductType,
                    ProductDetails = new Detail
                    {
                        Heigth = product.ProductDetails.Heigth,
                        Width = product.ProductDetails.Width,
                        Lenth = product.ProductDetails.Lenth
                    }
                    });
                context.SaveChanges();
            }

            return View();
        }

        [MyActionFilter]
        [MyExeptionFilter]
        public ActionResult ShowById(int? productId)
        {
            //if (ModelState.IsValid)
            //{
                if (productId.HasValue)
                {
                    var product = new Context().Products.Find(productId);
                    if (product != null)
                    {
                        return View(product);
                        //ViewBag.Message = $"Product Id = {product.ProductId}, Name = {product.Name}, Price = {product.Price}, Type = {product.ProductType.ToString()}. " +
                        //    $"Details: Length = {product.ProductDetails.Lenth}" +
                        //    $" Heigth = {product.ProductDetails.Heigth}" +
                        //    $" Width = {product.ProductDetails.Width}";
                    }
                    else
                    {
                        //TODO Fixed this exception
                        //throw new ProductIsNotFoundByIdException($"We haven`t found product by Id#{productId}");
                        ViewBag.Message = $"The product by Id - {productId} was not found!";
                    }
                }
            //}

            return View();
        }

        [OutputCache(Duration = 300)]
        [MyActionFilter]
        public ActionResult ShowList()
        {
            return View(new Context().Products);
        }

        [HttpGet]
        public ActionResult Check(string name)
        {
            var result = Regex.IsMatch(name, "^[a-zA-Z0-9 ]*$", RegexOptions.IgnoreCase);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SA_ASP.NET_MVC_Practice/Views/Log/Delete.cshtml
@model SA_ASP.NET_MVC_Practice.Models.Log

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Log</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Milliseconds)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Milliseconds)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameActionMethod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameActionMethod)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SA_ASP.NET_MVC_Practice/Views/Log/Details.cshtml
@model SA_ASP.NET_MVC_Practice.Models.Log

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
<div>
    <h4>Log</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Milliseconds)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Milliseconds)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameActionMethod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameActionMethod)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

SA_ASP.NET_MVC_Practice/Views/Log/Index.cshtml
@model IEnumerable<SA_ASP.NET_MVC_Practice.Models.Log>

@{
    ViewBag.Title = "List of logs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Milliseconds)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameActionMethod)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Milliseconds)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NameActionMethod)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

SA_ASP.NET_MVC_Practice/Views/Product/Add.cshtml
@model SA_ASP.NET_MVC_Practice.Models.Product

@{
    ViewBag.Title = "Add product";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Add", "Product", FormMethod.Post))
{
<div class="form-horizontal">
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.ProductId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.ProductId)
            @Html.ValidationMessageFor(m => m.ProductId)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Price, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Price)
            @Html.ValidationMessageFor(m => m.Price)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Description)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ProductType, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(m => m.ProductType)
        </div>
    </div>

    <h3>Details of product</h3>

    <div class="form-group">
        @Html.LabelFor(m => m.ProductDetails.Heigth, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.ProductDetails.Heigth)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ProductDetails.Lenth, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.ProductDetails.Lenth)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ProductDetails.Width, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.ProductDetails.Width)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add product" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SA_ASP.NET_MVC_Practice/Views/Product/Index.cshtml
<br />
@Html.ActionLink("Add product", "Add")
<br />
@Html.ActionLink("Show by product id", "ShowById")
<br />
@Html.ActionLink("Show list of products", "ShowList")
<br />

SA_ASP.NET_MVC_Practice/Views/Product/ShowById.cshtml
@model SA_ASP.NET_MVC_Practice.Models.Product

@{
    ViewBag.Title = "Details of product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<div>
    @if (Model != null)
    {
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ProductId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProductId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProductType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProductType)
            </dd>

            <dt>
                <u><b>Details of product:</b></u>
            </dt>

            <dd>

            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProductDetails.Heigth)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProductDetails.Heigth)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProductDetails.Lenth)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProductDetails.Lenth)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProductDetails.Width)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProductDetails.Width)
            </dd>

        </dl>
    }
    else
    {
        using (Html.BeginForm("ShowById", "Product", FormMethod.Post))
        {
        <div class="form-horizontal">
            <hr />
            <h3>@ViewBag.Message</h3>
            <div class="form-group">
                @Html.LabelFor(m => m.ProductId, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.EditorFor(m => m.ProductId)
                    @Html.ValidationMessageFor(m => m.ProductId)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Show product" class="btn btn-default" />
                </div>
            </div>
        </div>
        }
    }
</div>
<p>
    @Html.ActionLink("Back to List", "ShowList")
</p>





@*@model SA_ASP.NET_MVC_Practice.Models.Product

    @{
        ViewBag.Title = "Show product by Product Id";
    }

    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>

    @using (Html.BeginForm("ShowById", "Product", FormMethod.Post))
    {

        <div class="form-horizontal">
            <hr />
            <div class="form-group">
                @Html.LabelFor(m => m.ProductId, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.EditorFor(m => m.ProductId)
                    @Html.ValidationMessageFor(m => m.ProductId)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Show product" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

SA_ASP.NET_MVC_Practice/Views/Product/ShowList.cshtml
@model IEnumerable<SA_ASP.NET_MVC_Practice.Models.Product>

@{
    ViewBag.Title = "List of products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductType)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductType)
            </td>
            <td>
                @Html.ActionLink("Details of product", "ShowById", new { productId = item.ProductId })
            </td>
        </tr>
    }

</table>





@*@model IEnumerable<SA_ASP.NET_MVC_Practice.Models.Product>

@{
    ViewBag.Title = "List of products";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("ShowList", "Product", FormMethod.Post))
{
    <div class="form-horizontal">
        @foreach (var item in Model)
        {
            <hr />
            <div class="form-group">
                @Html.Label("Product Id:", new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.Label(item.ProductId.ToString())
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Name:", new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.Label(item.Name.ToString())
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Price:", new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.Label(item.Price.ToString())
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Type of product:", new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.Label(item.ProductType.ToString())
                </div>
            </div>
        }
    </div>}*@

SA_ASP.NET_MVC_Practice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("LOGS", "Index", "Log")</li>
                    <li>@Html.ActionLink("Add product", "Add", "Product")</li>
                    <li>@Html.ActionLink("List of products", "ShowList", "Product")</li>
                    <li>@Html.ActionLink("Find product by Id", "ShowById", "Product")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>